export const companylist = [
    {
        id:1,
        image:require('./images/company1.jpg'),
        companyname:"Balaji Web Technology",
        companyaddress:"Delhi,India",
        Duration:"2012-2015",
        jobresponsibilities:"job responsibilities:",
        job1: "1. Gathering Requirements",
        job2: "2. Designing Wireframes",
        job3: "3. Developing Content",
    },
    {
        id:2,
        image:require('./images/company2.jpeg'),
        companyname:"Systematic System Solutions",
        companyaddress:"Delhi,India",
        Duration:"2012-2015",
        jobresponsibilities:"job responsibilities:",
        job1: "1. Gathering Requirements",
        job2: "2. Designing Wireframes",
        job3: "3. Developing Content",
    },
    {
        id:3,
        image:require('./images/company3.jpg'),
        companyname:"JB Enterprises",
        companyaddress:"Delhi,India",
        Duration:"2012-2015",
        jobresponsibilities:"job responsibilities:",
        job1: "1. Gathering Requirements",
        job2: "2. Designing Wireframes",
        job3: "3. Developing Content",
    }/*
    {
        id:4,
        image:require('./images/interest.jpg'),
        companyname:"Balaji Web Technology",
        companyaddress:"Delhi,India",
        Duration:"2012-2015",
        jobresponsibilities:"job responsibilities:",
        job1: "1. Gathering Requirements",
        job2: "2. Designing Wireframes",
        job3: "3. Developing Content",
    }*/
]